export interface PickupDTO{
    assigned_on: string,
    carrier_id: number,
    completed_on: string,
    created_at: string,
    created_by: number,
    id: number,
    item_type: string,
    payer: string,
    payment_method: string,
    pickup_on: string,
    receiver_address: string,
    receiver_landmark: string,
    receiver_mobile: string,
    receiver_name: string,
    receiver_pin: string,
    sender_address: string,
    sender_landmark: string,
    sender_mobile: string,
    sender_name: string,
    sender_pin: string,
    status: string,
    updated_at: string,
    product_name: string,
    weight: string
}